# -*- coding: utf-8 -*-
"""Problem_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R5syp-gzfZMjAjbGBX4ieX0ZpsGnON5g
"""

def remove_duplicates(array):
    if not array:
        return []

    result = [array[0]]

    for i in range(1, len(array)):
        if array[i] != array[i - 1]:
            result.append(array[i])
    return result

input_string = input("Enter the original array: ")
sub_strings = input_string.split()
integers = map(int, sub_strings)
original_array = list(integers)

sorted_array = sorted(original_array)

result = remove_duplicates(sorted_array)

print("Original array:", original_array)
print("Sorted array:", sorted_array)
print("Array without duplicates:", result)

