# -*- coding: utf-8 -*-
"""Problem_0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BoHdBTCI0a8DQObkN4eVgUhqB07i8png
"""

def fib(n):
    if n == 0:
        return 0
    if n == 1:
        return 1
    return fib(n-1) + fib(n-2)

def debug_fib(n):
    result = fib(n)
    print(f"fib({n}) = {result}")
    return result

n = int(input("Enter any value to calculate Fibonacci sequence(n): "))
debug_fib(n)

