# -*- coding: utf-8 -*-
"""Problem_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l5dnhVlRiGx4VHUXkbqvA3mDXbB2-h_-
"""

def merge_sorted_arrays(arrays):
    result = []
    index = [0] * len(arrays)

    while True:
        min_value = None
        min_index = None

        for i, arr in enumerate(arrays):
            if index[i] < len(arr):
                if min_value is None or arr[index[i]] < min_value:
                    min_value = arr[index[i]]
                    min_index = i

        if min_value is None:
            break

        result.append(min_value)
        index[min_index] += 1

    return result

K = int(input("Enter the number of arrays (K): "))
N = int(input("Enter the size of each array (N): "))

arrays = []
for i in range(K):
    array = list(map(int, input(f"Enter elements for array {i + 1}: ").split()))
    arrays.append(array)

merged_array = merge_sorted_arrays(arrays)
print("Merged sorted array:", merged_array)

